services:
  estoualer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoualer
    restart: unless-stopped
    ports:
      - "4201:80"

networks:
  default:
    name: estoualer
